<?php
/**
 * Created by PhpStorm.
 * User: mxgel
 * Date: 30/09/2017
 * Time: 7:07 AM
 */

namespace Mxgel\MPesa\Responses;


use Mxgel\MPesa\Contracts\ResultCodesContract;
use Mxgel\MPesa\Model;

/**
 * Class B2B
 *
 * @package Mxgel\MPesa\Responses
 */
class Response extends Model implements ResultCodesContract
{
    /**
     * @var string
     */
    protected $merchantRequestID;
    /**
     * @var string
     */
    protected $checkoutRequestID;
    /**
     * @var string
     */
    protected $responseCode;
    /**
     * @var string
     */
    protected $resultDesc;
    /**
     * @var string
     */
    protected $resultCode;
    /**
     * @var string
     *
     * A unique numeric code generated by the M-Pesa system of the response to a request.
     */
    protected $conversationID;
    /**
     * @var string
     *
     * A unique numeric code generated by the M-Pesa system of the request.
     */
    protected $originatorConversationID;

    /**
     * @var string
     *
     * Safaricom's response bug
     */
    protected $originatorCoversationID;
    /**
     * @var string
     *
     * A response message from the M-Pesa system accompanying the response to a request.
     */
    protected $responseDescription;

    /**
     * @var string
     */
    protected $customerMessage;

    /**
     * @return null|string
     */
    public function getResponseCode(): ?string
    {
        return $this->responseCode;
    }

    /**
     * @param string $responseCode
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setResponseCode(string $responseCode): Response
    {
        $this->responseCode = $responseCode;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getResponseDescription(): ?string
    {
        return $this->responseDescription;
    }

    /**
     * @param string $responseDescription
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setResponseDescription(string $responseDescription): Response
    {
        $this->responseDescription = $responseDescription;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getOriginatorConversationID(): ?string
    {
        // For some reason, safaricom's API returns a misspelled `originatorCoversationID`.
        // Let's force this in
        return $this->originatorConversationID ?: $this->originatorCoversationID ?: '';
    }

    /**
     * @param string $originatorConversationID
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setOriginatorConversationID(string $originatorConversationID): Response
    {
        $this->originatorConversationID = $originatorConversationID;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getConversationID(): ?string
    {
        return $this->conversationID;
    }

    /**
     * @param string $conversationID
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setConversationID(string $conversationID): Response
    {
        $this->conversationID = $conversationID;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getMerchantRequestID(): ?string
    {
        return $this->merchantRequestID;
    }

    /**
     * @param string $merchantRequestID
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setMerchantRequestID(string $merchantRequestID): Response
    {
        $this->merchantRequestID = $merchantRequestID;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getCheckoutRequestID(): ?string
    {
        return $this->checkoutRequestID;
    }

    /**
     * @param string $checkoutRequestID
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setCheckoutRequestID(string $checkoutRequestID): Response
    {
        $this->checkoutRequestID = $checkoutRequestID;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getResultDesc(): ?string
    {
        return $this->resultDesc;
    }

    /**
     * @param string $resultDesc
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setResultDesc(string $resultDesc): Response
    {
        $this->resultDesc = $resultDesc;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getResultCode(): ?string
    {
        return $this->resultCode;
    }

    /**
     * @param string $resultCode
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setResultCode(string $resultCode): Response
    {
        $this->resultCode = $resultCode;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getCustomerMessage(): ?string
    {
        return $this->customerMessage;
    }

    /**
     * @param string $customerMessage
     *
     * @return \Mxgel\MPesa\Responses\Response
     */
    public function setCustomerMessage(string $customerMessage): Response
    {
        $this->customerMessage = $customerMessage;

        return $this;
    }

    /**
     * @return bool
     */
    public function completed()
    {
        return $this->getResultCode() == self::RESULT_SUCCESS;
    }
}